#!/usr/bin/env bash
# transfers a file from one client to another
# accepts for arguments:
#+ path to the file to be transfered
#+ IP of the server to transfer the file to
#+ Username that scp connects with
#+ Path to the ssh private key that scp uses

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrickHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
