#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "server { 
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html;
	server_name _;
	location / {
		return 200 'Hello World!';
	}
}" > /etc/nginx/sites-available/default
servive nginx start
fi
