#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# The name of the custom HTTP header must be X-Served-By
# The value must be the hostname of the server Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx
# confire firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'ssh'

sudo mkdir -p /var/www/html
# change mod to allow us to easily create files in this directory
sudo chmod -R 755 /var/www
sudo touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By '$HOSTNAME';
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

 
# restart nginx
sudo service nginx restart
