#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend www
    bind *:80
    mode http
    default_backend web_backend
backend web_backend
    balance roundrobin
    server gideon-web-01 52.87.255.0:80  check
    server gideon-web-02 52.3.244.163:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
