#!/usr/bin/env bash
# Bash script that: 
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself 
# when recieving a SIGQUIT and SIGTERM signal

pidfile=/var/run/myscript.pid
echo "$$" > "$pidfile"

function cleanup {
        rm "$pidfile"
        echo "Exiting..."
        exit 0
}

trap 'cleanup' SIGQUIT SIGTERM

trap 'echo "Y U no love me?!"' SIGINT

trap 'echo "I hate the kill command"' SIGTERM

while true
do
        echo "To infinity and beyond"
	sleep 2
done
