#!/usr/bin/env bash
# Bash script that displays lines containing the bash word
# allowing you to easily get the PID of your Bash process.
# third line of your script must be # shellcheck disable=SC2009
# cannot use pgrep

ps -aux | grep bash
