#!/usr/bin/env bash
# a Bash script that groups visitors by IP and HTTP status code, and displays this data.

awk '{count[$1" "$9]++} END {for (ip in count) {print count[ip], ip}}' apache-access.log | sort -rn
