#!/usr/bin/env bash
# Displays bad luck and good luck at 4th and 8th iteration and Best School else

count=0
while [ $count -gt 0 ]
do
	if [ $count -eq 6 ]
	then
		echo "bad luck"
	elif [ $count -eq 2 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$(( count - 1 ))
done
