#!/usr/bin/env bash
# displays bad luck and good luck at pos 4 and 8 and Best School else

count=10
while [ $count -gt 0 ]
do
	if [ $count -eq 6 ]
	then
		echo "bad luck"
	elif [ $count -eq 2 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$(( count - 1 ))
done
